# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('win', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('bowl_game', models.CharField(max_length=30)),
                ('coach', models.CharField(max_length=30)),
            ],
        ),
    ]
